// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://gnkgrlnirzpgqnzbgfcd.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdua2dybG5pcnpwZ3FuemJnZmNkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzMyNzI5MjgsImV4cCI6MjA0ODg0ODkyOH0.7xepDhC7Utp-8MwHaKIQQwgSMgx8cFDAvTjsaUnkedQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);